G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion

; set velocity / acceleration limits
SET_VELOCITY_LIMIT VELOCITY=200  ACCEL=5000  ACCEL_TO_DECEL=5000 SQUARE_CORNER_VELOCITY=5.66
START_PRINT EXTRUDER_TEMP=<TOOLTEMP> BED_TEMP=<HBPTEMP>
BED_MESH_PROFILE LOAD="default" ; load default bed mesh
SET_PRESSURE_ADVANCE ADVANCE=<FILAMENT> ; Linear/Pressure advance

; additionnal informations for Klipper web API (Moonraker)
; if feedback from Moonraker is implemented in the choosen web UI (Mainsail, Fluidd, Octoprint), this info will be used for gcode previewing
; Generated by TOGCODE SCRIPT
; print_height_mm : 0.08
; layer_count : 10
; filament_type : PLA
; filament_name : PLA
